version: '3.1'

services:
  auth-database:
    image: mysql:latest
    networks:
      - rabbitmq_app-network
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=userAuth
      - MYSQL_PASSWORD=12345

  auth-service:
    networks:
      - rabbitmq_app-network
    environment:
      - spring.datasource.username=root
      - spring.datasource.password=12345
      - spring.jpa.hibernate.dll-auto=update
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://auth-database:3306/userAuth?createDatabaseIfNotExist=true
      - spring.rabbitmq.addresses=rabbitmq:5672
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - auth-database
    ports:
      - 8081:8081
    restart: on-failure

networks:
  rabbitmq_app-network:
    external:
      name: rabbitmq_app-network
